"""Added the name for UQ index in the users table

Revision ID: 1f9edd978d2b
Revises: 3ffb7d82385e
Create Date: 2024-12-20 10:56:45.976045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f9edd978d2b'
down_revision = '3ffb7d82385e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('username')
        batch_op.create_unique_constraint('UQ_email', ['email'])
        batch_op.create_unique_constraint('UQ_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('UQ_username', type_='unique')
        batch_op.drop_constraint('UQ_email', type_='unique')
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
