"""Added the is_demo column to the users table

Revision ID: 3ed28a1e1897
Revises: 1f9edd978d2b
Create Date: 2024-12-23 09:44:35.790557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed28a1e1897'
down_revision = '1f9edd978d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_demo', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_demo')

    # ### end Alembic commands ###
