"""Named the indexes of the chapters table

Revision ID: 3ffb7d82385e
Revises: c23b7e684e53
Create Date: 2024-12-20 09:47:48.034835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ffb7d82385e'
down_revision = 'c23b7e684e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index('name')
        batch_op.drop_index('number')
        batch_op.create_unique_constraint('UQ_name', ['name'])
        batch_op.create_unique_constraint('UQ_number', ['number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_constraint('UQ_number', type_='unique')
        batch_op.drop_constraint('UQ_name', type_='unique')
        batch_op.create_index('number', ['number'], unique=True)
        batch_op.create_index('name', ['name'], unique=True)

    # ### end Alembic commands ###
