"""Added the description column to the chapters table

Revision ID: b243d01f19e3
Revises: ea41d5eefc7f
Create Date: 2024-12-13 10:11:12.126415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b243d01f19e3'
down_revision = 'ea41d5eefc7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
