"""Set the cascade configuration for the need relationships

Revision ID: e6fdbd461cc5
Revises: ed625b1e194c
Create Date: 2024-12-19 11:50:10.527042

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e6fdbd461cc5"
down_revision = "ed625b1e194c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("completed_chapters", schema=None) as batch_op:
        batch_op.drop_constraint("FK_completed_chapters_user_id", type_="foreignkey")
        batch_op.create_foreign_key(
            "FK_completed_chapters_user_id",
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("current_chapters", schema=None) as batch_op:
        batch_op.drop_constraint("FK_user_id", type_="foreignkey")
        batch_op.create_foreign_key(
            "FK_user_id", "users", ["user_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("current_chapters", schema=None) as batch_op:
        batch_op.drop_constraint("FK_user_id", type_="foreignkey")
        batch_op.create_foreign_key("FK_user_id", "users", ["user_id"], ["id"])

    with op.batch_alter_table("completed_chapters", schema=None) as batch_op:
        batch_op.drop_constraint("FK_completed_chapters_user_id", type_="foreignkey")
        batch_op.create_foreign_key(
            "FK_completed_chapters_user_id", "users", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###
