"""Added the completed_chapters table

Revision ID: ed625b1e194c
Revises: 5733c3dd2f15
Create Date: 2024-12-15 00:35:29.409725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed625b1e194c'
down_revision = '5733c3dd2f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_chapters',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name='FK_completed_chapters_chapter_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='FK_completed_chapters_user_id'),
    sa.PrimaryKeyConstraint('user_id', 'chapter_id', name='PK_completed_chapters')
    )
    with op.batch_alter_table('completed_chapters', schema=None) as batch_op:
        batch_op.create_index('idx_completed_chapters_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_chapters', schema=None) as batch_op:
        batch_op.drop_index('idx_completed_chapters_user_id')

    op.drop_table('completed_chapters')
    # ### end Alembic commands ###
